### ISSUE TITLE
Btc

### ISSUE THREAD

**Issue by roi35** [Rexagon/ton-address-miner#1]
Не актуально

**Comment by Rexagon** [comment]
В этой репе эксперимент с bip39 и расчётом адреса  для TON. Но он кажись провалился, т.к. pbkdf2 в читабельной реализации слишком медленный. Сами мнемоники очень быстро генерятся, а вот вывод ключей из них...

**Comment by roi35** [comment]
А если совместить GPU и вывод ключей через CPU?

**Comment by Rexagon** [comment]
Вывод на CPU я уже делал ([сам вывод](https://github.com/broxus/ton-msig/blob/master/src/utils/Mnemonic.cpp) и [простейший перебор](https://github.com/broxus/ton-msig/blob/master/src/ton-msig/AddressGenerator.cpp)). Но всё-таки в этом проекте попытаюсь соптимизировать и выполнить всё на GPU

**Comment by roi35** [comment]
А попробуете для биткоина ? Почему выбрали именно тон ? Он вроде не сильно популярен и не так много стоит .. я пробовал запустить по тону оно сгенерировала штук 7 мнемоник но я так и не понял где чекнуть баланс или воссоздать из мнемоников адрес что б чекнуть

**Comment by Rexagon** [comment]
В этом нет смысла, будут задержки на синхронизацию памяти и т.д.

**Comment by Rexagon** [comment]
Тон - из-за специфики работы. Майнер адресов - потому что хочу красивый адрес за разумное время. Вывело какие-то непонятные мнемоники - потому что это недоделанный проект и там в выводе промежуточные данные для тестов.

Для биткойна всё по другому будет, лучше ищите какие-нибудь специальные штуки для брута. В тоне ключ != адрес и всё есть контракт. Адрес контракта это хэш от его кода+начальных данных. Мнемоника связана с контрактом тем, что выведенный из неё публичный ключ является частью начальных данных контракта. Короче дурка

**Comment by roi35** [comment]
Жаль что не получится для биткоина.( для ETH тоже не выйдет ?
